# Generated by Django 4.1 on 2022-12-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_product_file_product_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='file',
        ),
    ]
